#! /bin/bash
#
# Helper to launch the service with activated virtualenv.
#
# The virtualenv needs to be active for uWSGI to work properly.

. /etc/default/conan
. /opt/venvs/conan/bin/activate

/usr/bin/conan start
